depot/config/routes.rb
Rails.application.routes.draw do
  resources :carts

  get 'store/index'

  resources :products

  root to: 'store#index', as: 'store' 

end

depot/app/models/cart.rb
class Cart < ActiveRecord::Base
end

depot/app/models/product.rb
class Product < ActiveRecord::Base
	 validates :title, :description, :image_url, presence: true
	 validates :price, numericality: {greater_than_or_equal_to: 0.01}
	 validates :title, uniqueness: true
	 validates :image_url, allow_blank: true, format: {
	 	with: %r{\.(gif|jpg|png)\Z}i,
	 	message: 'must be a URL for GIF, JPG or PNG image.'
 # URL должен указывать на изображение формата GIF, JPG или PNG
 }
 	def self.latest
 		Product.order(:updated_at).last
	end
end

depot/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

depot/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

depot/app/controllers/store_controller.rb
class StoreController < ApplicationController
  
  def index
  	@products = Product.order(:title)
  end

end

depot/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application",
  "data-turbolinks-track" => true %>
  <%= csrf_meta_tag %>
 </head>
 <body class="<%= controller.controller_name %>">
 	<div id="banner">
	 	<%= image_tag("logo.png") %>
	 	<%= @page_title || "Pragmatic Bookshelf" %>
	 </div>
	 <div id="columns">
	 <div id="side">
		 <ul>
			 <li><a href="http://www....">Home</a></li>
			 <li><a href="http://www..../faq">Questions</a></li>
			 <li><a href="http://www..../news">News</a></li>
			 <li><a href="http://www..../contact">Contact</a></li>
		</ul>
	 </div>
	 <div id="main">
	 	 <%= yield %>
	  </div>
	  </div>
  </body>
  </html>

depot/app/views/products/index.html.erb
<h1>Listing products</h1>
<table>
  <% @products.each do |product| %>
   <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
     <td><%= image_tag(product.image_url, class: 'list_image') %>
     </td>
     <td class="list_description">
        <dl>
            <dt><%= product.title %></dt>
            <dd><%= truncate(strip_tags(product.description), length: 80) %></dd> 
         </dl>
     </td>

      <td class="list_actions">
     <%= link_to 'Show', product %>
     <br/>

     <%= link_to 'Edit', edit_product_path(product) %>
     <br/>
     <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
     </td>
   </tr>
  <% end %>

</table>

<br />

<%= link_to 'New product', new_product_path %>

depot/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> title:</strong>
  <%= @product. title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

depot/app/views/store/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<h1>
	Your Pragmatic Catalog
</h1>
<% cache ['store', Product.latest] do %>
	<% @products.each do |product| %>
	 <% cache ['entry', product] do %>
	<div class="entry">
		 <%= image_tag(product.image_url) %>
		 <h3><%= product.title %></h3>
		 <%= sanitize(product.description) %>
		 <div class="price_line">
			 <span class="price"><%= number_to_currency(product.price) %></span>
		 </div>
	 </div>
	<% end %>
	<% end %>
	 
<% end %>